blank_issues_enabled: false
contact_links:
    - name: FAQ | سوالات متداول
      url: https://github.com/Starry-Sky-World/BPB-i18n/blob/main/docs/faq.md
      about: Before asking a question or presenting a problem, read through the frequently asked questions.